name: Build and Test ASP.Net Core app to an Azure Web App

env:
  DOTNET_VERSION: '9'

on:
  push:
    branches:
      - develop
    paths:
      - 'TennisCleanArchi.**'
      - '.github/workflows/dev-api-build-deploy.yml'
  pull_request:
    branches:
      - develop
    paths:
      - 'TennisCleanArchi.**'
      - '.github/workflows/dev-api-build-deploy.yml'
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build and run tests
        run: dotnet test